[package]
name = "riscv-rust-vmm-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kvm-ioctls = { path = "../kvm-ioctls" }
linux-loader = { path = "../linux-loader" }
vm-memory = "0.12.2"
